version: "3.9"

services:
    db_server:
        build:
            context: .
            dockerfile: ./Dockerfiles/Dockerfile_postgres
        image: postgres_server:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: school
    php_server:
        build:
            context: .
            dockerfile: ./Dockerfiles/Dockerfile_php
        image: php_server:latest
        ports:
            - "8080:80"
        volumes:
            - ./src/:/var/www/html/
